baseurl: /nyeri
permalink: pretty
markdown: kramdown
paginate: 5
repo: nyeri
github_org: maptime
maptime:
  chapter: MaptimeNyeri
  #twitter: TwitterHandle
  #disqus: YOUR DISQUS USERNAME
future: true

gems:
  - jekyll-feed
